---
title: "Mini-Project 2"
author: "Julia Hamilton, Zoe Rubinstein, Jessica Tin"
date: "March 24, 2017"
output: html_document
---


```{r, include=FALSE}
## Loading the data
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
 
# join candidates to house_elections
# look at candidates' votes, city, state, party
# visual/map?

house_elections <- house_elections %>%
  rename(cand_name=candidate_name) 
house_elections <- house_elections %>%
  filter(state=="PA") %>%
  arrange(district)
house_elections <- house_elections %>%
  mutate(cand_name=toupper(cand_name))
house_elections$cand_name <- gsub("\\.", "", house_elections$cand_name)

candidates <- candidates %>%
  filter(cand_office_state=="PA") %>%
  filter(cand_election_yr=="2012") %>%
  arrange(cand_office_district)
candidates <- candidates %>%
  rename(party=cand_party_affiliation) %>%
  rename(year=cand_election_yr) %>%
  rename(state=cand_office_state) %>%
  rename(district=cand_office_district)


glimpse(candidates)
glimpse(house_elections)


full_data<-inner_join(house_elections, candidates, by="cand_name")

```



```{r}
#renaming variables in order to help join data frames
candidates <-mutate(candidates, party=ifelse(party=='REP', 'R', party))
candidates <-mutate(candidates, party=ifelse(party=='DEM', 'D', party))  
candidates <-mutate(candidates, party=ifelse(party=='LIB', 'L', party))
candidates <-mutate(candidates, party=ifelse(party=='IND', 'I', party))

```

## cleaning up both data frames (will be done at end)

candidates <- candidates %>%
  select(cand_name, party, district, cand_city)


house_elections <- house_elections %>%
  select(district, cand_name, party, primary_votes)

```{r}
library(ggplot2)
library(maps)
library(dplyr)
library(ggthemes)

pa <- map_data("state") %>%
  subset(region == "pennsylvania")
counties <- map_data("county") %>%
  subset(region == "pennsylvania")

#to get the state boundaries
pa_map <- ggplot(data = pa, mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon(color = "black", fill = "gray") +
  ggtitle("Pennsylvania House Election Results by County") +
  theme_void()
    
#to distinguish county boundaries of the state
pa_map +
  geom_polygon(data = counties, color = "white", fill = NA) +
  geom_polygon(color = "black", fill = NA)

```

```{r}
data(us.cities)
map("state", "Pennsylvania")
map.cities(us.cities, country="PA")
```



