---
title: "Mini-Project 2"
author: "Julia Hamilton, Zoe Rubinstein, Jessica Tin"
date: "March 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message=FALSE, echo=TRUE)
```

```{r}
# Load the data
load("candidates.rda")
load("contributions.rda")
library(tidyverse)
```

```{r}
# Clean up candidates df to prepare for join
candidates1 <- candidates %>%
  filter(cand_office_state=="PA") %>% # Only use Pennsylvania data
  select(cand_id, cand_party_affiliation, cand_election_yr,
         cand_city, cand_zip) %>% # Keep columns with data of interest
  rename(zip_code = cand_zip)

# Clean up contributions df to prepare for join
contributions1 <- contributions %>%
  filter(state=="PA", transaction_type=="24E") %>% # Only use PA data and advocating contributions
  select(cand_id, transaction_amt)

money <- inner_join(candidates1, contributions1, by="cand_id") # Join candidates, contributions
money<-money%>%
  mutate(zip_code=as.numeric(zip_code))
```

```{r}
# Integrate zip codes
zip <- read.csv("~/Desktop/zip_codes.csv")

zip <- zip %>%
  select(Zip_Code, County) %>%
  rename(zip_code = Zip_Code) %>%
  mutate(County=toupper(County))

money1 <- inner_join(money, zip, by="zip_code")

pa_counties <- map_data("county", region = "pennsylvania")

pa_counties <- pa_counties %>%
  mutate(subregion=toupper(subregion)) %>%
  rename(County=subregion)

bigmoney <- inner_join(money1, pa_counties, by="County")

reps <- bigmoney %>%
  filter(cand_party_affiliation=="REP")
dems <- bigmoney %>%
  filter(cand_party_affiliation=="DEM")
```

```{r}
ggplot(money1, aes(y=transaction_amt, x=County)) + geom_point(aes(color=cand_party_affiliation, shape=cand_party_affiliation), position = position_jitter(width = 0.25, height = 0), size=2.5) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        panel.grid=element_blank(), 
        axis.title = element_text(family="CenturyGothic", face="bold", size=10, color="black"),
        legend.text = element_text(family="CenturyGothic", face="bold", size=10, color="black"),
        axis.ticks.length = unit(0.3, "cm"),
        legend.title = element_text(family="CenturyGothic", face="bold", size=10, color="black"),
        axis.text=element_text(family="CenturyGothic", face="bold", size=8, color="black"))
```



```{r}
# Function to get state data from candidates and contributions dfs
state_data <- function(cand_df, cont_df, state) {
  cands <- cand_df %>%
    filter(cand_office_state==state) %>%
    select(cand_id, cand_party_affiliation, cand_election_yr, cand_city, cand_zip) %>%
    rename(zip_code = cand_zip)
  
  conts <- cont_df %>%
    filter(state==state, transaction_type=="24E") %>%
    select(cand_id, transaction_amt)
  
  money_new <- inner_join(cands, conts, by="cand_id")
  return(money_new)
}

# Example call:
# state_data(cand_df=candidates, cont_df=contributions, state="NY")
```